columns:
 - Pregnancies : int64
 - Glucose : int64
 - BloodPressure : int64
 - SkinThickness : int64
 - Insulin : int64
 - BMI : float64
 - DiabetesPedigreeFunction : float64
 - Age : int64
 - Outcome : int64

numerical_columns: 
 - Pregnancies
 - Glucose
 - BloodPressure
 - SkinThickness
 - Insulin
 - BMI
 - DiabetesPedigreeFunction
 - Age
 - Outcome
 